---
apiVersion: v1
kind: Service
metadata:
  name: examapp-service
  labels:
    app: examapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: examapp-port
  selector:
    app: examapp